#pragma once

#include "draw.h"

#define FRAMEBUFFER_TOP_SIZE       SCREEN_SIZE
#define FRAMEBUFFER_BUTTOM_SIZE    SCREEN_SIZE
/*#define FRAMEBUFFER_TOP_LEFT_1  ((vu8*)0x20184E60) // BGR
#define FRAMEBUFFER_TOP_LEFT_2  ((vu8*)0x201CB370)
#define FRAMEBUFFER_TOP_RIGHT_1 ((vu8*)0x20282160)
#define FRAMEBUFFER_TOP_RIGHT_2 ((vu8*)0x202C8670)
#define FRAMEBUFFER_BUTTOM_1    ((vu8*)0x202118E0)
#define FRAMEBUFFER_BUTTOM_2    ((vu8*)0x20249CF0)*/
#define FRAMEBUFFER_TOP_LEFT_1  ((vu8*)TOP_SCREEN0) // BG
#define FRAMEBUFFER_TOP_LEFT_2  ((vu8*)TOP_SCREEN1)
#define FRAMEBUFFER_TOP_RIGHT_1 ((vu8*)TOP_SCREEN0)
#define FRAMEBUFFER_TOP_RIGHT_2 ((vu8*)TOP_SCREEN1)
#define FRAMEBUFFER_BUTTOM_1    ((vu8*)BOT_SCREEN0)
#define FRAMEBUFFER_BUTTOM_2    ((vu8*)BOT_SCREEN1)

void clear_screens(u8 param);
